server:
  servlet:
    context-path: /zz
    jsp:
      init-parameters:
        development: true
  port: 8989
spring:
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://localhost:3306/bolo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #username: root
    #password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    view:
      suffix: /
      prefix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true #开启
      #data:
      #elasticsearch:
      #cluster-nodes: 192.168.124.201:9300
  jpa:
    show-sql: true #开启sql显示
#mybatis:
  #mapper-locations: classpath:com/zz/demo/mapper/*Mapper.xml
  #type-aliases-package: com.zz.demo.entity
#pagehelper:
  #support-methods-arguments: true
  #helper-dialect: mysql
  #params: count=countSql
  #reasonable: true